from typing import Any, Optional

class BaseGeometry(object):
    def almost_equals(self, other: "BaseGeometry", decimal: int = 6) -> bool: ...
    def buffer(self, distance: float, resolution: int = 16, quadsegs: Optional[Any] = None, cap_style: int = 1, join_style: int = 1, mitre_limit: float = 0.5) -> "BaseGeometry": ...
class BaseMultipartGeometry(object): ...
