from typing import Any, Dict, Iterable, List, Union

from numpy import ndarray

class DataFrame(object):
    def __getitem__(self, index: str) -> Any: ...
    def __setitem__(self, index: str, value: Any) -> None: ...
    def __init__(
        self, data: Union[ndarray, DataFrame, Dict[str, Any], None] = None
    ) -> None: ...
    def copy(self) -> DataFrame: ...
    def itertuples(self) -> Iterable[Any]: ...
    def set_index(self, keys: Union[str, List[str]]) -> DataFrame: ...

def concat(dfs: List[DataFrame]) -> DataFrame: ...
def read_csv(filepath_or_buffer: str) -> DataFrame: ...

class Series(object):
    def __getitem__(self, index: int) -> Any: ...
